import express from "express";
import router from "./routes/authRoutes";
import financialRouter from "./routes/financialProfile.routes";
import cookieParser from "cookie-parser";
import { errorMiddleware } from "./middlewares/errorMiddleware";
import subscriptionRouter from "./routes/subscription.routes";
import expenseRouter from "./routes/expense.routes";
import getDashboard from "./routes/dashboard.routes";
import dashboardRouter from "./routes/dashboard.routes";
const app = express();

app.use(express.json());
app.use(cookieParser());
app.use("/api/v1/auth", router);
app.use("/api/v1/financial", financialRouter);
app.use("/api/v1/subscription", subscriptionRouter);
app.use("/api/v1/expense", expenseRouter);
app.use("/api/v1/dashboard", dashboardRouter);
app.use(errorMiddleware);
export default app;
